config/routes.rb
Rails.application.routes.draw do
  devise_for :players, :controllers => { omniauth_callbacks: "players/omniauth_callbacks", sessions: "players/sessions" }, skip: [:registration]

  resources :boards do
    resources :records do
    end

    member do
      get  'players'
      post 'create_player'
      delete 'destroy_player/:bp_id', to: 'boards#destroy_player', as: 'destroy_player'

      post 'create_game'
      post 'update_game'
    end

    collection do
      get 'search', to: 'boards#search_player', as: 'search_player'
    end
  end

  root 'index#index'
end

app/views/index/index.html.haml
.panel
  .panel-heading
    %span.panel-title
      %i.panel-title-icon.fa.fa-smile-o
    .panel-heading-controls
      %span.panel-heading-text
        = link_to t('helpers.add'), new_board_path, class: "btn btn-xs btn-success"
        \&nbsp;&nbsp;
        - if @boards.count > 15
          %span.text-light-gray
            |
          \&nbsp;&nbsp;
      = will_paginate @boards, class: "pagination-xs", renderer: BootstrapPagination::Rails, previous_label: '«', next_label: '»'
    / / .panel-heading-controls
  / / .panel-heading
  %table.table
    %thead
      %tr
        %th.col-md-3= t('date')
        %th= t('title')
        %th= t('wager')
        %th
    %tbody.valign-middle
      - @boards.each do |board|
        %tr
          %td= l(board.created_at, format: :ymds)
          %td= link_to board.title, board_path(board)
          %td= board.wager
          %td
            .pull-right
              = link_to t('helpers.edit'), edit_board_path(board), class: "btn btn-xs"
              = link_to t('helpers.delete'), board_path(board), class: "btn btn-xs", method: :delete, data: {confirm: t('helpers.are_you_sure_delete')}