config/routes.rb
Rails.application.routes.draw do
  devise_for :players, :controllers => { omniauth_callbacks: "players/omniauth_callbacks", sessions: "players/sessions" }, skip: [:registration]

  resources :boards do
    resources :records do
    end

    member do
      get  'players'
      post 'create_player'
      delete 'destroy_player/:bp_id', to: 'boards#destroy_player', as: 'destroy_player'

      post 'create_game'
      post 'update_game'
    end

    collection do
      get 'search', to: 'boards#search_player', as: 'search_player'
    end
  end

  root 'index#index'
end

app/models/record.rb
class Record < ActiveRecord::Base
  belongs_to :board
  belongs_to :board_player
end

app/controllers/records_controller.rb
class RecordsController < ApplicationController

  def index
    board = Board.find(params[:board_id])
    @record = Record.where(board: board).order(created_at: :desc)
    @players = Record.where(board: board).select(:player_id, :anonymous).distinct
  end

  def show

  end

  def new
    @record = Record.new
  end

  def edit
  end

  def create
    @record = Record.new(record_params)
    if @record.save
      redirect_to board_records_path
    else
      render :new
    end
  end

  def update
    @record = Record.update(record_params)
  end

  def destroy
    @record.destroy
    redirect_to board_records_path
  end

  private
    def set_record
      @record = Record.find(params[:id])
    end

    def record_params
      params.require(:record).permit(:player, :score)
    end
end

app/helpers/records_helper.rb
module RecordsHelper
end

app/views/records/index.html.haml
.panel
  .panel-heading
    %span.panel-title
      %i.panel-title-icon.fa.fa-smile-o
    .panel-heading-controls
      %span.panel-heading-text
        = link_to t('helpers.setting_player'), new_board_record_path, class: "btn btn-xs btn-success"
        \&nbsp;&nbsp;
        %span.text-light-gray
          |
        \&nbsp;&nbsp;
      %ul.pagination.pagination-xs
        %li
          %a{:href => "#"} «
        %li.active
          %a{:href => "#"} 1
        %li
          %a{:href => "#"} 2
        %li
          %a{:href => "#"} 3
        %li
          %a{:href => "#"} »
    / / .panel-heading-controls
  / / .panel-heading
  %table.table
    %thead
      %tr
        %th.col-md-3= t('date')
        - @players.each do |player|
          - if player.anonymous?
            %th= player.anonymous
          - else
            %th= player.player.name
    %tbody.valign-middle
      - @record.each do |record|
        %tr
          %td= record.created_at
          - if record.anonymous?
            %td= record.anonymous
          - else
            %td= record.player.name
          %td= record.score

app/views/records/new.html.haml
.page-header
  %h1
    %span= t('helpers.setting_player')
.row
  .col-md-12
    = render 'form'