config/routes.rb
Rails.application.routes.draw do
  devise_for :players, :controllers => { omniauth_callbacks: "players/omniauth_callbacks", sessions: "players/sessions" }, skip: [:registration]

  resources :boards do
    resources :records do
    end

    member do
      get  'players'
      post 'create_player'
      delete 'destroy_player/:bp_id', to: 'boards#destroy_player', as: 'destroy_player'

      post 'create_game'
      post 'update_game'
    end

    collection do
      get 'search', to: 'boards#search_player', as: 'search_player'
    end
  end

  root 'index#index'
end

app/models/board.rb
class Board < ActiveRecord::Base
  belongs_to :player
  has_many   :records
  has_many   :board_players

  def save_of_user(current_player)
    self.player = current_player
    save
  end
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController

  before_action :set_board, only: [:show, :players, :edit, :update, :destroy]

  def new
    @board = Board.new
  end

  def show
    @bps       = BoardPlayer.where(board: @board)
    @records   = Record.includes(:board, :board_player).order(created_at: :desc)
    @score_sum = Record.where(board: @board).group(:board_player_id).sum(:score)
    @new_game  = Record.new
  end

  def edit
  end

  def create
    @board = Board.new(board_params)
    if @board.save_of_user(current_player)
      redirect_to root_path
    else
      render :new
    end
  end

  def update
    if @board.update(board_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  def destroy
    @board.destroy
    redirect_to root_path
  end

  # Game
  def create_game
    if params[:scores].size == params[:board_players].size
      scores = params[:scores]
      scores.each_with_index do |score, i|
        record = Record.new({board_id: params[:id], board_player_id: params[:board_players][i], score: score})
        t = record.save
        Rails.logger.debug { "+++++ #{record.to_json}" }
      end
    end
    redirect_to board_path
  end

  def update_game

    redirect_to board_path
  end
  # --

  # Player
  def players
    @new_bp = BoardPlayer.new
    @bps    = BoardPlayer.where({board: @board})
  end

  def search_player
    @players = Player.where('name like ?', "#{params[:name]}%")
  end

  def create_player
    bp = BoardPlayer.new(board_player_params)
    redirect_to players_board_path if bp.save_of_board(params[:id])
  end

  def destroy_player
    BoardPlayer.find(params[:bp_id]).delete
    redirect_to players_board_path
  end
  # --

  private
    def set_board
      @board = Board.find(params[:id])
    end

    def board_params
      params.require(:board).permit(:master, :title, :wager)
    end

    def board_player_params
      params.require(:board_player).permit(:board_id, :player_id, :anonymous)
    end
end

app/helpers/boards_helper.rb
module BoardsHelper
  def board_player_name(board_player)
    if board_player.anonymous
      board_player.anonymous
    else
      board_player.player.name
    end
  end

  def options_from_wager(wager)
    result = []
    range_base = 300
    Array(-range_base..range_base).each {|num| result.push([num * wager, num * wager]) }
    options_for_select(result, 0)
  end

  def recored_transform(bps, records)
    new_records = []
    bps_arr = []

    bps.each { |bp| bps_arr.push(bp.id) }

    record_arr = Array.new(bps.size , 0)
    cr = tmp_cr = nil
    records.each_with_index do |record, i|
      cr = record.created_at
      tmp_cr = record.created_at if i == 0

      if cr.to_s != tmp_cr.to_s
        tmp_cr = record.created_at
        record_arr[0] = tmp_cr
        new_records.push(record_arr)
        record_arr = Array.new(bps.size + 1, 0)
      end
      record_arr[bps_arr.index(record.board_player_id) + 1] = record.score
    end
    record_arr[0] = tmp_cr
    new_records.push(record_arr)
    new_records
  end
end

app/views/boards/_form.html.haml
= form_for @board do |f|
  .form-group{class: ('has-error' if @board.errors.include? :title)}
    = f.label :title, t('boards.title'), class: 'control-label'
    = f.text_field :title, class: 'form-control', placeholder: t('boards.placeholder.title')
    - if @board.errors.include? :title
      %p.help-block
        - @board.errors[:title].each do |message|
          = message
  .form-group{class: ('has-error' if @board.errors.include? :wager)}
    = f.label :wager, t('boards.wager'), class: 'control-label'
    = f.number_field :wager, class: 'form-control', placeholder: t('boards.placeholder.wager')
    - if @board.errors.include? :wager
      %p.help-block
        - @board.errors[:wager].each do |message|
          = message
  .form-group
    .pull-right
      = link_to t('helpers.back'), root_path, class: 'btn btn-default btn-flat'
      = f.submit t('helpers.add'), class: 'btn btn-success btn-flat'

app/views/boards/edit.html.haml
.page-header
  %h1
    %span= t('helpers.edit')

.row
  .col-md-12
    = render 'form'

app/views/boards/new.html.haml
.page-header
  %h1
    %span= t('helpers.add')

.row
  .col-md-12
    = render 'form'

app/views/boards/players.html.haml
.page-header
  %h1
    = link_to board_path(params[:id]), data: {toggle: "tooltip", placement: "bottom", "original-title"=> @board.title} do
      %i.fa.fa-chevron-left
    %span= t('helpers.set_player')
.panel
  .panel-heading
    %span.panel-title= t('helpers.players')

  %table.table
    %thead
      %tr
        %th.col-md-2
          = link_to '#new_player', class: 'btn btn-xs btn-primary', data: {target: '#new_player', toggle: 'modal'} do
            %i.fa.fa-user-plus
            = t('helpers.new_player')
        %th= t('helpers.player')
    %tbody
      - @bps.each do |bp|
        %tr
          %td= link_to t('helpers.delete'), destroy_player_board_path(params[:id], bp), method: :delete
          %td
            - if bp.anonymous
              = bp.anonymous
            - else
              = image_tag "http://graph.facebook.com/v2.2/#{bp.player.uid}/picture?type=normal", size: "24x24", alt: bp.player.name
              = bp.player.name

#new_player.modal.fade{:role => "dialog", :style => "display: none;", :tabindex => "-1"}
  .modal-dialog{ style: "z-index: 1060;"}
    .modal-content
      = form_for @new_bp, url:create_player_board_path do |f|
        = f.hidden_field :player_id
        .modal-header
          %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", :type => "button"} ×
          %h4.modal-title= t('helpers.new_player')
        .modal-body
          = f.label :anonymous, t('boars_players.anonymous'), class: 'control-label'
          = f.text_field :anonymous, class: 'form-control', autocomplete: 'off'
          %br/
          .players.hide
            .panel.widget-messages-alt
              / / .panel-heading
              .panel-body.padding-sm
                .messages-list
                .message.sample.hide
                  %img.message-avatar{:alt => "", :src => ""}
                  %a.message-subject{:href => "#"}
                -# %a.messages-link{:href => "#"} MORE MESSAGES
              / / .panel-body
        .modal-footer
          = f.submit t('helpers.cancel'), class: 'btn btn-default btn-flat', data: {dismiss: 'modal'}
          = f.submit t('helpers.add'), class: 'btn btn-success btn-flat'
    / / .modal-content
  / / .modal-dialog
/ / .modal

app/views/boards/show.html.haml
.panel
  .panel-body
    = link_to '#new_game', class: 'btn btn-xs btn-danger', data: {target: '#new_game', toggle: 'modal'} do
      %i.fa.fa-game
      = t('helpers.new_game')
    \&nbsp;&nbsp;
    = link_to t('helpers.set_player'), players_board_path, class: "btn btn-info btn-xs"
    -# .pull-right
      -# %a.btn.btn-info.btn-xs{href: '#'}= t('helpers.game_mode')
.panel
  .panel-heading
    %span.panel-title
      %i.panel-title-icon.fa.fa-bars
      = @board.title
    .panel-heading-controls
      -# = will_paginate @records, class: "pagination-xs", renderer: BootstrapPagination::Rails, previous_label: '«', next_label: '»'
    / / .panel-heading-controls
  / / .panel-heading
  %table.table.table-hover
    %thead
      %tr
        %th.col-md-1
        - @bps.each do |bp|
          %th.text-center
            = board_player_name(bp)
            (
            %span{class: @score_sum[bp.id] > 0 ? 'win-score': ''}= @score_sum[bp.id]
            )
    %tbody.valign-middle
      - all_records = recored_transform(@bps, @records)
      - all_records.each_with_index do |records, rindex|
        %tr
          - records.each_with_index do |record, index|
            - if index == 0
              %td.text-center
                %span{data: {toggle: "tooltip", placement: "bottom", "original-title"=> l(record, format: :ymds)}}
                  = "##{all_records.size - rindex}"
            - else
              %td.text-center{class: record > 0 ? 'win-score': ''}= record

#new_game.modal.fade{:role => "dialog", :style => "display: none;", :tabindex => "-1"}
  .modal-dialog{ style: "z-index: 1060;"}
    .modal-content
      = form_for @new_game, url:create_game_board_path do |f|
        .modal-header
          %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", :type => "button"} ×
          %h4.modal-title= t('helpers.new_game')
        .modal-body
          - @bps.each do |bp|
            = label_tag board_player_name(bp), nil, class: 'control-label'
            = select_tag 'scores[]', options_from_wager(@board.wager), {class: 'form-control'}
            = hidden_field_tag 'board_players[]', bp.id
            %br/
        .modal-footer
          = f.submit t('helpers.cancel'), class: 'btn btn-default btn-flat', data: {dismiss: 'modal'}
          = f.submit t('helpers.clearing'), class: 'btn btn-success btn-flat'

#edit_game.modal.fade{:role => "dialog", :style => "display: none;", :tabindex => "-1"}
  .modal-dialog{ style: "z-index: 1060;"}
    .modal-content
      = form_for @new_game, url:update_game_board_path do |f|
        .modal-header
          %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", :type => "button"} ×
          %h4.modal-title= t('helpers.edit_game')
        .modal-body
          - @bps.each do |bp|
            = label_tag board_player_name(bp), nil, class: 'control-label'
            = select_tag 'scores[]', options_from_wager(@board.wager), {class: 'form-control'}
            = hidden_field_tag 'board_players[]', bp.id
            %br/
        .modal-footer
          = f.submit t('helpers.cancel'), class: 'btn btn-default btn-flat', data: {dismiss: 'modal'}
          = f.submit t('helpers.clearing'), class: 'btn btn-success btn-flat'