config/routes.rb
Rails.application.routes.draw do
  devise_for :players, :controllers => { omniauth_callbacks: "players/omniauth_callbacks", sessions: "players/sessions" }, skip: [:registration]

  resources :boards do
    resources :records do
    end

    member do
      get  'players'
      post 'create_player'
      delete 'destroy_player/:bp_id', to: 'boards#destroy_player', as: 'destroy_player'

      post 'create_game'
      post 'update_game'
    end

    collection do
      get 'search', to: 'boards#search_player', as: 'search_player'
    end
  end

  root 'index#index'
end

app/views/common/_footer.html.haml
%section.footer
  .container
    .pull-left
      © 2015 Big-Two Scoreboard

    .pull-right
      jiunjiun /
      quietmes@gmail.com

    %span.logo
      -# = image_tag("icon/icon_b_32.png", alt: "Big-Two Scoreboard", class: "logo")

app/views/common/_nav.html.haml
#main-navbar.navbar.navbar-inverse{:role => "navigation"}
  .navbar-inner
    / Main navbar header
    .navbar-header
      / Logo
      %a.navbar-brand{:href => root_path}
        -# = image_tag("icon/icon_32.png", alt: "Redesign", size: "24x24", class: "menu_icon")
        Big-Two Scoreboard
      / Main navbar toggle
      %button.navbar-toggle.collapsed{"data-target" => "#main-navbar-collapse", "data-toggle" => "collapse", :type => "button"}
        %i.navbar-icon.fa.fa-bars
    / / .navbar-header
    #main-navbar-collapse.collapse.navbar-collapse.main-navbar-collapse
      / / .navbar-nav
      .right.clearfix
        %ul.nav.navbar-nav.pull-right.right-navbar-nav
          - if player_signed_in?
            %li
              = link_to "#", class: "user-menu"  do
                = image_tag "http://graph.facebook.com/v2.2/#{current_player.uid}/picture?type=normal", size: "24x24", alt: current_player.name
                %span
                  %strong= current_player.name
              %li
                = link_to destroy_player_session_path, method: :delete, data: {toggle: "tooltip", placement: "bottom", "original-title"=> t('sign_out')} do
                  %i.fa.fa-power-off
          - else
            %li
              = button_to player_omniauth_authorize_path(:facebook), class: 'btn btn-primary btn-flat navbar-btn' do
                %i.fa.fa-facebook
                = t('sign_in')
          / / .navbar-nav
        / / .right
    / / #main-navbar-collapse
  / / .navbar-inner